services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm-nginx
    volumes:
      - qloapps_data:/home/qloapps/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - mariadb
    networks:
      - qloapps-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.php.loadbalancer.server.port=80"
      - "traefik.http.routers.php.entrypoints=web"
      - "traefik.http.routers.php.middlewares=corsheader@docker"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolalloworiginlist=https://${DOMAIN}"
      - "traefik.http.middlewares.corsheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.corsheader.headers.addvaryheader=true"

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-qloapps}
      MYSQL_USER: ${MYSQL_USER:-qloapps}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-qloappspassword}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
      - ./logs:/var/log/mysql
    networks:
      - qloapps-network

networks:
  qloapps-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  qloapps_data:
    driver: local
