services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        ENVIRONMENT: development
    volumes:
      - ./config_dev:/home/qloapps/config
      - ./admin:/home/qloapps/adm
      - ./themes:/home/qloapps/themes
    ports:
      - "9003:9003"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_START_WITH_REQUEST: yes
      ENVIRONMENT: development
    extra_hosts:
      - "host.docker.internal:host-gateway"
