services:
  php:
    volumes:
      - /mnt/blockstorage/app/themes:/home/qloapps/themes:rw
      - /mnt/blockstorage/app/adm:/home/qloapps/adm:rw
      - /mnt/blockstorage/app/img:/home/qloapps/img:rw
      - /mnt/blockstorage/app/config:/home/qloapps/config:rw
      - /mnt/blockstorage/app/backups:/home/qloapps/adm/backups:rw
      - /mnt/blockstorage/app/modules:/home/qloapps/modules:rw
      - /mnt/blockstorage/app/download:/home/qloapps/download:rw
      - /mnt/blockstorage/app/pdf:/home/qloapps/pdf:rw
      - /mnt/blockstorage/app/upload:/home/qloapps/upload:rw
      - /mnt/blockstorage/app/logs:/tmp/logs:rw
      - /mnt/blockstorage/app/override:/home/qloapps/override:rw
      - /mnt/blockstorage/app/robots.txt:/home/qloapps/robots.txt:rw
      - /mnt/blockstorage/app/.htaccess:/home/qloapps/.htaccess:rw
      - /mnt/blockstorage/app/qso_sitemap_cms_pages.xml:/home/qloapps/qso_sitemap_cms_pages.xml:rw
      - /mnt/blockstorage/app/qso_sitemap_hotels.xml:/home/qloapps/qso_sitemap_hotels.xml:rw
      - /mnt/blockstorage/app/qso_sitemap_room_types.xml:/home/qloapps/qso_sitemap_room_types.xml:rw
      - /mnt/blockstorage/app/sitemap_index.xml:/home/qloapps/sitemap_index.xml:rw
    environment:
      REMOVE_INSTALL_ADMIN: "yes"
    tmpfs:
      - /tmp/qloapps
    ports: []

  mariadb:
    volumes:
      - /opt/database:/var/lib/mysql


