services:
  php:
    volumes:
      - /mnt/blockstorage/app/themes:/home/qloapps/themes:rw
      - /mnt/blockstorage/app/adm:/home/qloapps/adm:rw
      - /mnt/blockstorage/app/img:/home/qloapps/img:rw
      - /mnt/blockstorage/app/config:/home/qloapps/config:rw
      - /mnt/blockstorage/app/backups:/home/qloapps/adm/backups:rw
      - /mnt/blockstorage/app/modules:/home/qloapps/modules:rw
      - /mnt/blockstorage/app/download:/home/qloapps/download:rw
      - /mnt/blockstorage/app/pdf:/home/qloapps/pdf:rw
      - /mnt/blockstorage/app/upload:/home/qloapps/upload:rw
      - /mnt/blockstorage/QloApps/classes:/home/qloapps/classes:rw
    environment:
      REMOVE_INSTALL_ADMIN: "yes"
    tmpfs:
      - /tmp/qloapps
    ports: []

  mariadb:
    volumes:
      - /opt/database:/var/lib/mysql


