services:
  php:
    volumes:
      - /opt/themes:/home/qloapps/themes:rw
      - /opt/adm:/home/qloapps/adm:rw
      - /opt/img:/home/qloapps/img:rw
      - /mnt/blockstorage/config:/home/qloapps/config:rw
      - /opt/backups:/home/qloapps/adm/backups:rw
      - /opt/modules:/home/qloapps/modules:rw
      - /opt/download:/home/qloapps/download:rw
      - /opt/pdf:/home/qloapps/pdf:rw
    environment:
      REMOVE_INSTALL_ADMIN: yes
    tmpfs:
      - /tmp/qloapps
    ports: []

  mariadb:
    volumes:
      - /opt/database:/var/lib/mysql


