services:
  php:
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - mariadb
    networks:
      - public
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.php.tls=true"
        - "traefik.http.routers.php.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.php.entrypoints=websecure"
        - "traefik.http.routers.php.tls.certresolver=myresolver"
        - "traefik.http.routers.php.middlewares=corsheader@swarm"
        - "traefik.http.middlewares.corsheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
        - "traefik.http.middlewares.corsheader.headers.accesscontrolallowheaders=*"
        - "traefik.http.middlewares.corsheader.headers.accesscontrolalloworiginlist=https://${DOMAIN}"
        - "traefik.http.middlewares.corsheader.headers.accesscontrolmaxage=100"
        - "traefik.http.middlewares.corsheader.headers.addvaryheader=true"
        - "traefik.http.services.php.loadbalancer.server.port=80"


  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-qloapps}
      MYSQL_USER: ${MYSQL_USER:-qloapps}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-qloappspassword}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
      - ./logs:/var/log/mysql
    networks:
      - public

networks:
  public:
    external: true

volumes:
  mariadb_data:
    driver: local
  qloapps_data:
    driver: local
