version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm-nginx
    volumes:
      - qloapps_data:/home/qloapps/www
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - qloapps-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.php.loadbalancer.server.port=80"
      - "traefik.http.routers.php.entrypoints=web"

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-qloapps}
      MYSQL_USER: ${MYSQL_USER:-qloapps}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-qloappspassword}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - qloapps-network

networks:
  qloapps-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  qloapps_data:
    driver: local
