services:
  php:
    volumes:
      - qloapps_data:/home/qloapps
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports: []

  mariadb:
    volumes:
      - /opt/database:/var/lib/mysql

  traefik:
    image: traefik:v3.0.1
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.mytlschallenge.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - qloapps-network
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.acme-challenge.entrypoints=web"
      - "traefik.http.routers.acme-challenge.rule=PathPrefix(`/.well-known/acme-challenge/`)"
      - "traefik.http.routers.acme-challenge.priority=2"
      - "traefik.http.routers.redirect-to-https.entrypoints=web"
      - "traefik.http.routers.redirect-to-https.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.redirect-to-https.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.redirect-to-https.priority=1"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    networks:
      - qloapps-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`shell.${DOMAIN}`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.entrypoints=web"

volumes:
  letsencrypt:
    driver: local
