version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm-nginx
    volumes:
      - .:/home/qloapps/www
      - /var/run/php/:/var/run/php/
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - qloapps-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.php.loadbalancer.server.port=80"
      - "traefik.http.routers.php.entrypoints=web"

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-qloapps}
      MYSQL_USER: ${MYSQL_USER:-qloapps}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-qloappspassword}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - qloapps-network

  traefik:
    image: traefik:v3.0.1
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8888:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - qloapps-network

networks:
  qloapps-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
